<?xml version="1.0"?>
<wsdl:definitions
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:tns="urn:ANDR_service"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
        xmlns:ns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        xmlns:ns1="http://www.w3.org/2000/09/xmldsig#"
        name="ANDR_service"
        targetNamespace="urn:ANDR_service">
<wsdl:types>
    <xsd:schema xmlns:tns="urn:ANDR_service" targetNamespace="urn:ANDR_service">
        <xsd:import namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" />
    </xsd:schema>
</wsdl:types>
<message name="WORKRequest">
    <part name="data" type="xsd:string" />
</message>
<message name="WORKResponse">
    <part name="return" type="xsd:string" />
</message>
<portType name="ANDR_servicePort">
    <operation name="WORK">
        <input message="tns:WORKRequest" />
        <output message="tns:WORKResponse" />
    </operation>
</portType>
<binding name="ANDR_serviceBinding" type="tns:ANDR_servicePort">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="WORK">
        <soap:operation soapAction="http://www.samo.ru/xml#ANDR_service#WORK" />
        <input>
            <soap:body use="encoded" namespace="http://www.samo.ru/xml" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
        </input>
        <output>
            <soap:body use="encoded" namespace="http://www.samo.ru/xml" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
        </output>
    </operation>
</binding>
<service name="ANDR_serviceService">
    <documentation />
    <port name="ANDR_servicePort" binding="tns:ANDR_serviceBinding">
        <soap:address location="${onlineurl}modules/andromeda_3/service.php" />
    </port>
</service>
</wsdl:definitions>
