<?php
get_help_button('onlinest:sistema_upravlenija:search_tour'); $SAVE = isset($_POST['SAVE']); $params = [ 'Section' => 'search', 'What' => 'FORCE_ROUND', 'UserCode' => INTERNET_USER, ]; $paramsOnlineConfig = [ 'SEARCH_TOURTYPE_FILTER', 'SEARCH_PROGRAMTYPE_FILTER', 'SEARCH_INCOMINGPARTNER_FILTER', 'SEARCH_UFILTER', 'REC_ON_PAGE', 'SHOW_OLD_PRICE', 'DEFAULT_GROUP_BY_HOTEL', ]; if ($SAVE) { if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['FORCE_ROUND'])) { $params['Value'] = intval($_POST['FORCE_ROUND']); } foreach ($paramsOnlineConfig as $name) { if (isset($_REQUEST[$name])) { $sql = $db->formatExec( OFFICE_SQLSERVER . '.' . OFFICEDB . '.dbo.up_WEB_3_ADMIN_tour_config', [ 'Section' => 'online_config', 'What' => $name, 'Value' => $_REQUEST[$name], 'UserCode' => ($name == 'INTERNET_USER') ? null : INTERNET_USER, ] ); $db->query($sql); } } } $sql = $db->formatExec('<OFFICEDB>.dbo.up_WEB_3_ADMIN_tour_config', $params); $res = $db->fetchRow($sql); $FORCE_ROUND = ($res) ? $res['Value'] : 0; $config = get_online_tour_config(); $value = isset($config['REC_ON_PAGE']) ? $config['REC_ON_PAGE'] : -1; $ADDITIONAL = '
    <hr>
    ' . Get_Message_Lang($LNG, 'adm_search_tour_force_round') . ':&nbsp;        
            <select name="FORCE_ROUND" style="margin-bottom: 10px;">
                <option value="0" ' . ($FORCE_ROUND ? '' : 'selected="selected"') . ' >' . Get_Message_Lang($LNG, 'adm_config_no') . '</option>
                <option value="1" ' . (!$FORCE_ROUND ? '' : 'selected="selected"') . ' >' . Get_Message_Lang($LNG, 'adm_config_yes') . '</option>
            </select><br>   
    ' . Get_Message_Lang($LNG, 'adm_search_tourtype_filter') . ':&nbsp;        
            <select name="SEARCH_TOURTYPE_FILTER" style="margin-bottom: 10px;">
                <option value="0" ' . ((!isset($config['SEARCH_TOURTYPE_FILTER']) || $config['SEARCH_TOURTYPE_FILTER'] == 0) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_no') . '</option>
                <option value="1" ' . ((isset($config['SEARCH_TOURTYPE_FILTER']) && $config['SEARCH_TOURTYPE_FILTER'] == 1) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_yes') . '</option>
            </select><br>   
    ' . Get_Message_Lang($LNG, 'adm_search_programtype_filter') . ':&nbsp;       
            <select name="SEARCH_PROGRAMTYPE_FILTER" style="margin-bottom: 10px;">
                <option value="0" ' . ((!isset($config['SEARCH_PROGRAMTYPE_FILTER']) || $config['SEARCH_PROGRAMTYPE_FILTER'] == 0) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_no') . '</option>
                <option value="1" ' . ((isset($config['SEARCH_PROGRAMTYPE_FILTER']) && $config['SEARCH_PROGRAMTYPE_FILTER'] == 1) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_and groups_and_types') . '</option>
                <option value="2" ' . ((isset($config['SEARCH_PROGRAMTYPE_FILTER']) && $config['SEARCH_PROGRAMTYPE_FILTER'] == 2) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_only_group') . '</option>
                <option value="3" ' . ((isset($config['SEARCH_PROGRAMTYPE_FILTER']) && $config['SEARCH_PROGRAMTYPE_FILTER'] == 3) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_only_types') . '</option>
            </select><br>   
    ' . Get_Message_Lang($LNG, 'adm_search_incoming_filter') . ':&nbsp;        
            <select name="SEARCH_INCOMINGPARTNER_FILTER" style="margin-bottom: 10px;">
                <option value="0" ' . ((!isset($config['SEARCH_INCOMINGPARTNER_FILTER']) || $config['SEARCH_INCOMINGPARTNER_FILTER'] == 0) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_no') . '</option>
                <option value="1" ' . ((isset($config['SEARCH_INCOMINGPARTNER_FILTER']) && $config['SEARCH_INCOMINGPARTNER_FILTER'] == 1) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_drop_down_list') . '</option>
                <option value="2" ' . ((isset($config['SEARCH_INCOMINGPARTNER_FILTER']) && $config['SEARCH_INCOMINGPARTNER_FILTER'] == 2) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_multiple_choise') . '</option>
            </select><br> 
    ' . Get_Message_Lang($LNG, 'adm_search_ufilter') . ':&nbsp;        
            <select name="SEARCH_UFILTER" style="margin-bottom: 10px;">
                <option value="0" ' . ((!isset($config['SEARCH_UFILTER']) || $config['SEARCH_UFILTER'] == 0) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_no') . '</option>
                <option value="1" ' . ((isset($config['SEARCH_UFILTER']) && $config['SEARCH_UFILTER'] == 1) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_yes') . '</option>
            </select><br> 
    ' . Get_Message_Lang($LNG, 'adm_config_show_old_price') . ':&nbsp;        
                <select name="SHOW_OLD_PRICE" style="margin-bottom: 10px;">
                    <option value="0" ' . ((!isset($config['SHOW_OLD_PRICE']) || $config['SHOW_OLD_PRICE'] == 0) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_no') . '</option>
                    <option value="1" ' . ((isset($config['SHOW_OLD_PRICE']) && $config['SHOW_OLD_PRICE'] == 1) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_yes') . '</option>
                </select><br>
    ' . Get_Message_Lang($LNG, 'adm_config_group_by_hotel') . ':&nbsp;        
                <select name="DEFAULT_GROUP_BY_HOTEL" style="margin-bottom: 10px;">
                    <option value="0" ' . ((!isset($config['DEFAULT_GROUP_BY_HOTEL']) || $config['DEFAULT_GROUP_BY_HOTEL'] == 0) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_no') . '</option>
                    <option value="1" ' . ((isset($config['DEFAULT_GROUP_BY_HOTEL']) && $config['DEFAULT_GROUP_BY_HOTEL'] == 1) ? 'selected="selected"' : '') . ' >' . Get_Message_Lang($LNG, 'adm_config_yes') . '</option>
                </select><br>  
'; $max_nights_count = 70; $max_adult_count = 30; $max_child_count = 30; $sql = $db->formatExec( OFFICE_SQLSERVER . '.' . OFFICEDB . '.dbo.up_WEB_3_tour_config', [ 'Section' => 'Tourist', 'What' => 'MaxChildAge', 'UserCode' => INTERNET_USER, ] ); $max_child_age = $db->fetchOne($sql); $values = array( 'MIN_PEOPLE' => array('type' => 'select', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_min_people'), 'possible_values' => range(0, $max_adult_count)), 'MAX_PEOPLE' => array('type' => 'select', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_max_people'), 'possible_values' => range(0, $max_adult_count)), 'MIN_CHILD' => array('type' => 'select', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_min_child'), 'possible_values' => range(0, $max_child_count)), 'MAX_CHILD' => array('type' => 'select', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_max_child'), 'possible_values' => range(0, $max_child_count)), 'CHILD_SMALL_AGES' => array('type' => 'select', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_child_small_ages'), 'selected' => 4, 'possible_values' => range(0, $max_child_age)), 'CHILD_MIDDLE_AGES' => array('type' => 'select', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_child_middle_ages'), 'selected' => 6, 'possible_values' => range(0, $max_child_age)), 'CHILD_BIG_AGES' => array('type' => 'select', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_child_big_ages'), 'selected' => 8, 'possible_values' => range(0, $max_child_age)), 'ADULTCOUNT' => array( 'type' => 'select', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_adultcount'), 'possible_values' => function () { return range(0, $GLOBALS['settings']['MAX_PEOPLE']['Value']); } ), 'CHILDCOUNT' => array( 'type' => 'select', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_childcount'), 'possible_values' => function () { return range(0, $GLOBALS['settings']['MAX_CHILD']['Value']); } ), 'night_from' => array('type' => 'select', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_nights_from'), 'possible_values' => range(0, $max_nights_count)), 'night_till' => array('type' => 'select', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_nights_till'), 'possible_values' => range(0, $max_nights_count)), 'places' => array('type' => 'checkbox', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_places')), 'stop_selling' => array('type' => 'checkbox', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_stop_selling')), 'moment_confirm' => array('type' => 'checkbox', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_moment_confirm')), 'all_currency' => array('type' => 'checkbox', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_all_currency')), 'child_in_bed' => array('type' => 'checkbox', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_child_in_bed')), 'note' => array('type' => 'note', 'title' => Get_Message_Lang($LNG, 'adm_search_tour_note')), ); $SECTION = 'search'; include _ROOT . 'admin/includes/online-tour-config.php'; 