<?php
$MODULE = 'd_available_hotels'; if (!defined('ROUTES_PATH')) { define('ROUTES_PATH', _ROOT . 'routes.php'); } include_once ROUTES_PATH; if (!isset($routes[$MODULE])) { die(Get_Message_Lang($LNG, 'adm_module_disabled')); } ?>
    <body>
<?php get_help_button('onlinest:sistema_upravlenija:remote_host_block') ?>
<?= style_css() ?>
<FORM name="start" action="" method="post">
    <input type="hidden" name="LNG" value="<?= $LNG ?>">
    <input type=hidden name="SAVE" value="">
<?php
if (!isset($CHECKIN1) or ($CHECKIN1 == '')) { $date1 = date('d/m/Y'); } else { $date1 = $CHECKIN1; } if (!isset($CHECKIN2) or ($CHECKIN2 == '')) { $date2 = mktime(0, 0, 0, date('m'), date('d') + 7, date('Y')); $date2 = date('d/m/Y', $date2); } else { $date2 = $CHECKIN2; } $CHECKIN1 = $date1; if (isset($_POST['CHECKIN1']) or isset($_GET['CHECKIN1'])) { $CHECKIN1 = isset($_POST['CHECKIN1']) ? $_POST['CHECKIN1'] : $_GET['CHECKIN1']; } Check_Date($CHECKIN1); $CHECKIN2 = $date2; if (isset($_POST['CHECKIN2']) or isset($_GET['CHECKIN2'])) { $CHECKIN2 = isset($_POST['CHECKIN2']) ? $_POST['CHECKIN2'] : $_GET['CHECKIN2']; } Check_Date($CHECKIN2); $TOURINC = 0; if (isset($_POST['TOURINC']) or isset($_GET['TOURINC'])) { $TOURINC = isset($_POST['TOURINC']) ? $_POST['TOURINC'] : $_GET['TOURINC']; } Is_Digital($TOURINC); set_time_limit(0); $str = ''; $partner_not_found = 0; $PARTNER = -2; $PARTTYPE = 0; if (!isset($CHECKIN1) or ($CHECKIN1 == '')) { $date1 = date('d/m/Y'); } else { $date1 = $CHECKIN1; } if (!isset($CHECKIN2) or ($CHECKIN2 == '')) { $date2 = mktime(0, 0, 0, date('m'), date('d') + 7, date('Y')); $date2 = date('d/m/Y', $date2); } else { $date2 = $CHECKIN2; } if (!isset($TOURINC) or ($TOURINC == '')) { $TOURINC = -1; } $a_inc_h = array(); $a_name_h = array(); $a_lname_h = array(); $sql = $db->formatExec( '<OFFICEDB>.[dbo].[up_WEB_3_ADMIN_d_xxx_all_tour]', [ 'USER' => $USER, 'dataset' => 1, ] ); if ($res = $db->fetchAll($sql)) { foreach ($res as $row) { if ($TOURINC < 0) { $TOURINC = $row['inc']; } $a_inc_h[] = htmlspecialchars($row['inc'], ENT_QUOTES, 'cp1251'); $a_name_h[] = htmlspecialchars($row['name'], ENT_QUOTES, 'cp1251'); $a_lname_h[] = htmlspecialchars($row['lname'], ENT_QUOTES, 'cp1251'); } } $result = false; if ($TOURINC > 0 and $date1 <> '' and $date2 <> '') { $d1 = substr($date1, 6, 4) . substr($date1, 3, 2) . substr($date1, 0, 2); $d2 = substr($date2, 6, 4) . substr($date2, 3, 2) . substr($date2, 0, 2); $af = array(); $sql = $db->formatExec( OFFICE_SQLSERVER . '.' . OFFICEDB . '.dbo.up_WEB_3_ADMIN_d_Hotel_Monitor', [ 'DateBeg' => $d1, 'DateEnd' => $d2, 'Tour' => $TOURINC, ] ); if ($result = $db->fetchAll($sql)) { foreach ($result[0] as $key => $value) { if (substr($key, 0, 1) == 'f') { $af[] = substr($key, 1, 8); } } } } $file_template = 'template.php'; include $file_template; 